@startuml
scale 1200 width

package controllers {
    class StartSystemController
    class CloseSystemController
    class PlanProjectController
    class OpenPhasesController
    class OpenIterationsController
    class OpenIterationController
    class AssignActivityController
    class ReestimateActivityController
    class MergeActivityController
    class SplitActivityController
    class CloseActivityController
    class OpenMembersController
    class CreateMemberController
    class UpdateMemberController
    class DeleteMemberController
    class OpenUseCasesController
    class CreateUseCaseController
    class UpdateUseCaseController
    class DeleteUseCaseController
    class PrioritizeUseCasesController
}

package views {
    interface Dialog
    interface ConfirmationDialog

    class MenuView
    class IterationView
    class InitProjectView
    class PlanProjectView
    class ProjectManagementView
    class PhaseView
    class MembersManagementView
    class UseCasesManagementView

    class AssignActivityDialog implements Dialog
    class CreateMemberDialog implements Dialog
    class UpdateMemberDialog implements Dialog
    class CreateUseCaseDialog implements Dialog

    class CloseActivityDialog implements ConfirmationDialog
    class DeleteUseCaseDialog implements ConfirmationDialog
    class DeleteMemberDialog implements ConfirmationDialog
}

package model {
    class Member
    class UseCase
    class Iteration
    Class Activity
    class Project
    class Phase
}

package helpers {
    class TimeInterval
}

@enduml
